
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xfb\xf8\xfa\xec\xdc\xcb(\x91Iq\x02\xb7\xfd\x07F\x82'
    
_lr_action_items = {'QUIT':([0,],[1,]),'DIRECTION':([0,9,],[2,19,]),'DROP':([0,],[6,]),'WORD':([3,6,8,10,11,13,14,17,18,],[11,11,11,11,11,11,11,11,11,]),'LOOK':([0,],[4,]),'INSPECT':([0,],[3,]),'NUMBER':([6,8,],[14,17,]),'TO':([9,],[18,]),'TAKE':([0,],[8,]),'GO':([0,],[9,]),'AT':([4,],[13,]),'$end':([1,2,4,5,7,11,12,15,16,19,20,21,22,23,24,25,],[-10,-2,-9,-13,0,-15,-11,-6,-4,-1,-8,-14,-12,-7,-5,-3,]),'EAT':([0,],[10,]),'INVENTORY':([0,],[5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[7,]),'words':([3,6,8,10,11,13,14,17,18,],[12,15,16,20,21,22,23,24,25,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> GO DIRECTION','command',2,'p_command_go','informPlay.py',42),
  ('command -> DIRECTION','command',1,'p_command_direction','informPlay.py',50),
  ('command -> GO TO words','command',3,'p_command_goto','informPlay.py',58),
  ('command -> TAKE words','command',2,'p_command_take','informPlay.py',77),
  ('command -> TAKE NUMBER words','command',3,'p_command_takeNumber','informPlay.py',101),
  ('command -> DROP words','command',2,'p_command_drop','informPlay.py',123),
  ('command -> DROP NUMBER words','command',3,'p_command_dropNumber','informPlay.py',153),
  ('command -> EAT words','command',2,'p_command_eat','informPlay.py',179),
  ('command -> LOOK','command',1,'p_command_look','informPlay.py',207),
  ('command -> QUIT','command',1,'p_command_quit','informPlay.py',211),
  ('command -> INSPECT words','command',2,'p_command_inspect','informPlay.py',215),
  ('command -> LOOK AT words','command',3,'p_command_inspect','informPlay.py',216),
  ('command -> INVENTORY','command',1,'p_command_inventory','informPlay.py',234),
  ('words -> WORD words','words',2,'p_words','informPlay.py',257),
  ('words -> WORD','words',1,'p_words','informPlay.py',258),
]
